#!/usr/bin/env bash
curl -s 'https://api.github.com/repos/JuliaLang/julia/releases' | 
python3 -c " 
import sys, json
file=json.load(sys.stdin)
for obj in file:
    print(obj['tag_name'].strip('v'))
"
